apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: Always
  pathConfig:
    path: "/var/hpvolumes"
    useNamingPrefix: true
  workload:
    nodeSelector:
      kubernetes.io/os: linux

